<Project>
  <PropertyGroup>
    <Version>3.7.7</Version>
    <PackageVersion>0.12.7</PackageVersion>
    <Copyright>sa_ddam213 - 2026</Copyright>
    <RepositoryUrl>https://github.com/saddam213/AmuseAI</RepositoryUrl>
    <Authors>sa_ddam213</Authors>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Configurations>Debug;Release;Release-Installer;</Configurations>
    <PlatformTarget>x64</PlatformTarget>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <TargetFrameworks>net10.0-windows10.0.17763.0</TargetFrameworks>
  </PropertyGroup>
</Project>